# Essential Basic functionality

In [1]:
import pandas as pd
import numpy as np

index = pd.date_range("1/1/2000", periods=8)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

df

A         B         C
2000-01-01  0.550438  0.005530  0.488416
2000-01-02 -0.615294  1.257800  1.783242
2000-01-03  1.288192 -1.786406  0.036037
2000-01-04 -0.214622 -1.853983 -0.314454
2000-01-05 -0.738276 -0.444347  0.598828
2000-01-06  0.949435  0.238033 -1.083492
2000-01-07 -0.973412 -0.791514  0.658125
2000-01-08  1.253396 -0.767878  1.478246

## Attributes and Underlying Data

In [2]:
df[:2]

A        B         C
2000-01-01  0.550438  0.00553  0.488416
2000-01-02 -0.615294  1.25780  1.783242

In [3]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2000-01-01  0.550438  0.005530  0.488416
2000-01-02 -0.615294  1.257800  1.783242
2000-01-03  1.288192 -1.786406  0.036037
2000-01-04 -0.214622 -1.853983 -0.314454
2000-01-05 -0.738276 -0.444347  0.598828
2000-01-06  0.949435  0.238033 -1.083492
2000-01-07 -0.973412 -0.791514  0.658125
2000-01-08  1.253396 -0.767878  1.478246

In [4]:
s.array

<PandasArray>
[ -2.361473820634825, -0.5223838196032475,  -1.550990876200261,
 -0.9743532864844281,  1.2321794389693728]
Length: 5, dtype: float64

In [5]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [6]:
#how to use a numpy array.

s.to_numpy()

array([-2.36147382, -0.52238382, -1.55099088, -0.97435329,  1.23217944])

In [7]:
#Also using a numpy array.

np.asarray(s)

array([-2.36147382, -0.52238382, -1.55099088, -0.97435329,  1.23217944])

In [8]:
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))

ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET')], dtype=object)

## Accelerated Operations

In [9]:
# Pandas has support for accelerated certain types of binary numerical and boolean operations using the `numexpr` library and the `bottleneck` libraries.

#Thes are both enabled to be used by default, you can control this by the options:

pd.set_option("compute.use_bottleneck", False)
pd.set_options("compute.use_numexpr", False)

AttributeError: module 'pandas' has no attribute 'set_options'

## Flexible binary operations

 - Broadcasting behaviour between higher - (e.g DataFrame) and lower-dimensional (e.g series) object.
 
  - Missing data computations.

### Matching / broadcasting behaviour.

 - DataFrame has the methods add(), sub(), mul(), div() and related functions radd(), rsub() for carrying out binary operations.

In [10]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)
df

one       two     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [11]:
row = df.iloc[1]

column = df["two"]

df.sub(row, axis="columns")

one       two     three
a -0.583554  0.288623       NaN
b  0.000000  0.000000  0.000000
c  0.486292 -0.041325 -0.706763
d       NaN -0.021972 -1.443609

In [12]:
df.sub(row, axis=1)

one       two     three
a -0.583554  0.288623       NaN
b  0.000000  0.000000  0.000000
c  0.486292 -0.041325 -0.706763
d       NaN -0.021972 -1.443609

In [13]:
df.sub(column, axis="index")

one  two     three
a -1.465872  0.0       NaN
b -0.593695  0.0  0.388206
c -0.066078  0.0 -0.277233
d       NaN  0.0 -1.033432

In [14]:
df.sub(column, axis=0)

one  two     three
a -1.465872  0.0       NaN
b -0.593695  0.0  0.388206
c -0.066078  0.0 -0.277233
d       NaN  0.0 -1.033432

In [15]:
dfmi = df.copy()

dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]
)

dfmi.sub(column, axis=0, level="second")

one       two     three
first second                              
1     a      -1.465872  0.000000       NaN
      b      -0.593695  0.000000  0.388206
      c      -0.066078  0.000000 -0.277233
2     a            NaN -0.310595 -1.344027

In [16]:
#divmod() - takes the floor division and modulo operation at the same time returning a two-tuple of the same type as the left hand side

s = pd.Series(np.arange(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [17]:
div, rem = divmod(s, 3)

div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int32

In [18]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

In [19]:
idx = pd.Index(np.arange(10))
idx

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')

In [20]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

### Missing Data / operations with fill values.

In [21]:
df2 = df.copy()

df2["three"]["a"] = 1.0

df

one       two     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [22]:
df2

one       two     three
a -1.125195  0.340677  1.000000
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [23]:
df + df2

one       two     three
a -2.250390  0.681353       NaN
b -1.083283  0.104107  0.880518
c -0.110700  0.021457 -0.533009
d       NaN  0.060163 -2.006701

In [24]:
df.add(df2, fill_value=0)

one       two     three
a -2.250390  0.681353  1.000000
b -1.083283  0.104107  0.880518
c -0.110700  0.021457 -0.533009
d       NaN  0.060163 -2.006701

### Flexible Comparisons

In [25]:
# Series and DataFrames have the binary comparison methods `eq`, `ne`, `lt`, `gt`, `le` and 'ge'.
# whose behaviour is analogous to the binary arithmetic operations described above:

df.gt(df2)

one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [26]:
df2.ne(df)

one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

### Boolean Reductions

In [27]:
# You can apply the reductions: `empty`, `any()`, `all()`, `bool` to provide a way to summarize a boolean result.

(df > 0).all()

one      False
two       True
three    False
dtype: bool

In [28]:
(df > 0).any()

one      False
two       True
three     True
dtype: bool

In [29]:
#You can reduce to a final boolean value.

(df > 0).any().any()

True

In [30]:
# Testing if a pandas is empty, via the `empy` property.
df.empty

False

In [31]:
pd.DataFrame(columns=list("ABC")).empty

True

### Comparing if Objects are Equivalent

In [32]:
# Testing if df + df and df * 2 produce the same result.

# Using: (df + df == df * 2).all() is a false expression.

df + df == df * 2

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [33]:
(df + df == df * 2).all()

# NaNs do no compute as equal.

one      False
two       True
three    False
dtype: bool

In [ ]:
np.nan == np.nan

In [34]:
# NDFrames(Series and DataFrames) have an equal() method for testing equality, with NaNs in corresponding locations treated as equal.

(df + df).equals(df * 2)

True

In [35]:
# Series and DataFrames needs to be in the same order for equality to be True:

df1 = pd.DataFrame({"col": ["foo", 0, np.nan]})

df2 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])

df1.equals(df2)

False

In [36]:
df1.equals(df2.sort_index())

True

### Comparing array-like objects.

In [37]:
# You can conveniently perform element-wise comparisons when comparing a pandas data structure with scalar value:

pd.Series(["foo", "bar", "baz"]) == "foo"

0     True
1    False
2    False
dtype: bool

In [38]:
pd.Index(["foo", "bar", "baz"]) == "foo"

array([ True, False, False])

In [39]:
# pandas also handles element-wise comparisons between different array-like objects of the same length:

pd.Series(["foo", "bar", "baz"]) == pd.Index(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

In [40]:
pd.Series(["foo", "bar", "baz"]) == np.array(["foo", "bar", "qux"])

0     True
1     True
2    False
dtype: bool

- Tryng to compare `index` or `series` objects of different lengths will raise a ValueError

### Combining Overlapping DataSets.

 - The function implementing this operation is `combine_first()`

In [41]:
df1 = pd.DataFrame(
    {"A": [1.0, np.nan, 3.0, 5.0, np.nan], "B": [np.nan, 2.0, 3.0, np.nan, 6.0]}
)


df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [42]:
df2 = pd.DataFrame(
    {
        "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
        "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],
    }
)

df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [43]:
df1.combine_first(df2)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

### General DataFrame combine

 - The combine_first() method calls the more general `DataFrame.combine()` which takes another DataFrame and combiner function, aligns the input DataFrame and then passes the combiner function pairs of Series.

In [44]:
# To reproduce the combine_first() : 

def combiner(x, y):
    return np.where(pd.isna(x), y, x)

df1.combine(df2, combiner)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

## Descriptive Statistics

In [45]:
df

one       two     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [46]:
df.mean(0)

one     -0.574062
two      0.108385
three   -0.276532
dtype: float64

In [47]:
# The `skipna` option signals whether to exclude missing data.

df.sum(0, skipna=False)

one          NaN
two      0.43354
three        NaN
dtype: float64

In [48]:
df.sum(axis=1, skipna=True)

a   -0.784519
b   -0.049329
c   -0.311126
d   -0.973269
dtype: float64

In [49]:
ts_stand = (df - df.mean()) / df.std()

ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [50]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

- Methods like `cumsum()` and `cumprod()` preserve the location of NaN values.
- This is somewhat different from `expanding()` and `rolling()` since NaN behaviour is furthermore dictated by a `min_periods` parameter.

In [51]:
df.cumsum()

one       two     three
a -1.125195  0.340677       NaN
b -1.666837  0.392730  0.440259
c -1.722187  0.403458  0.173755
d       NaN  0.433540 -0.829596

In [52]:
#returning the number of unique non-NA values in a series.

series = pd.Series(np.random.randn(500))

series[20:500] = np.nan

series[10:20] = 5

series.nunique()

11

### Summarizing data: describe

In [53]:
series = pd.Series(np.random.randn(1000))

series[::2] = np.nan

series.describe()

count    500.000000
mean       0.002630
std        0.986353
min       -2.752732
25%       -0.656070
50%        0.027432
75%        0.680610
max        2.562415
dtype: float64

In [54]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=["a", "b", "c", "d", "e"])

frame.iloc[::2] = np.nan

frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean     0.089158    0.064037   -0.011616   -0.010966    0.108295
std      0.982667    1.014306    0.998990    1.051125    1.005034
min     -2.752247   -3.352704   -2.776238   -3.641799   -2.853886
25%     -0.539158   -0.621823   -0.694723   -0.752001   -0.582885
50%      0.107111    0.093262   -0.030653    0.032694    0.103424
75%      0.739268    0.739249    0.693458    0.737688    0.784715
max      3.184272    3.270510    3.024545    2.646750    3.165764

In [55]:
# we can select specific percentiles to include in the output:

series.describe(percentiles=[0.5, 0.25, 0.75, 0.95])

count    500.000000
mean       0.002630
std        0.986353
min       -2.752732
25%       -0.656070
50%        0.027432
75%        0.680610
95%        1.633550
max        2.562415
dtype: float64

In [56]:
# for non-numeric series object, describe() will give a simple summary of the number of unique values and most frequently occurring values:

pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])

s.describe()

count    10.00000
mean      4.50000
std       3.02765
min       0.00000
25%       2.25000
50%       4.50000
75%       6.75000
max       9.00000
dtype: float64

In [57]:
# On a mixed -type Dataframe object, describe() will restrict the summary to include only numerical columns or, if none are, only ctegorical columns:

frame = pd.DataFrame({"a" : ["Yes", "Yes", "No", "No"], "b": range(4)})

frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [58]:
frame.describe(include=["object"])

a
count     4
unique    2
top     Yes
freq      2

In [59]:
frame.describe(include=["number"])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [60]:
frame.describe(include="all")

a         b
count     4  4.000000
unique    2       NaN
top     Yes       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

### Index of min/max values
 - `idxmin()` and `idxmax()` functions on Series and DataFrame compute the index labels with the minimum and maximum corresponding values.

In [61]:
s1 = pd.Series(np.random.randn(5))

s1

0    0.976613
1    0.907415
2    1.026578
3   -0.753323
4    1.002936
dtype: float64

In [63]:
s1.idxmin(), s1.idxmax()

(3, 2)

In [66]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])

df1

A         B         C
0  0.184341  1.973255  1.179310
1  1.195827  0.300103 -1.258058
2 -0.325726 -1.468301 -0.578871
3 -1.180914  2.340455  0.591329
4  1.212710 -0.894976 -1.588944

In [67]:
df1.idxmin(axis=0)

A    3
B    2
C    4
dtype: int64

In [68]:
df1.idxmax(axis=1)

0    B
1    A
2    A
3    B
4    A
dtype: object

In [ ]:
# idxmin and idxmax are called argmin and argmax in Numpy

### Value Counts (histogramming) / mode

In [70]:
# value_counts() Series method computes a histogram of 1D array of values
#It can als be used as a function on regukar arrays:

data = np.random.randint(0, 7, size=50)

data

array([2, 1, 4, 6, 6, 1, 1, 4, 0, 6, 6, 5, 3, 4, 6, 4, 3, 2, 2, 1, 3, 6,
       6, 1, 2, 3, 3, 6, 2, 1, 6, 6, 6, 2, 1, 4, 6, 2, 4, 5, 2, 0, 4, 6,
       1, 1, 3, 6, 0, 5])

In [75]:
s = pd.Series(data)

s.value_counts()

6    14
1     9
2     8
4     7
3     6
0     3
5     3
Name: count, dtype: int64

In [76]:
# value_counts() method uses all columns but a subset can be selected using the `subset` arguement.

data = {"a":[1, 2, 3, 4], "b":["x", "x", "y", "y"]}

frame = pd.DataFrame(data)

frame.value_counts()

a  b
1  x    1
2  x    1
3  y    1
4  y    1
Name: count, dtype: int64

In [79]:
#getting the most frequently occuring values (mode)

s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7,7])

s5.mode()

0    3
1    7
dtype: int64

In [81]:
df5 = pd.DataFrame(
    {
        "A" : np.random.randint(0, 7, size=50),
        "B" : np.random.randint(-10, 15, size=50),
    }
)

df5.mode()

A   B
0  3.0 -10
1  NaN  -5
2  NaN  11
3  NaN  13

### Discretization and quantiling
- Continuous values can be discretized using the `cut()` (bins based on values) and `qcut()` (bins based on sample quantiles) functions:

In [82]:
arr = np.random.randn(20)

factor = pd.cut(arr, 4)

factor

[(-0.452, 0.416], (-1.324, -0.452], (-0.452, 0.416], (1.285, 2.154], (-0.452, 0.416], ..., (-0.452, 0.416], (-0.452, 0.416], (-0.452, 0.416], (-1.324, -0.452], (-1.324, -0.452]]
Length: 20
Categories (4, interval[float64, right]): [(-1.324, -0.452] < (-0.452, 0.416] < (0.416, 1.285] < (1.285, 2.154]]

In [83]:
factor = pd.cut(arr, [5, -1, 0, 1, 5])

factor

ValueError: bins must increase monotonically.

In [85]:
# qcut() computes sample quantiles eg - slicing up some normally distributed data into equal-size quartiles like:

arr = np.random.randn(30)

factor = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1])

factor

[(-0.455, 0.259], (0.259, 0.587], (-0.455, 0.259], (0.587, 3.132], (-0.455, 0.259], ..., (-0.455, 0.259], (0.259, 0.587], (-2.201, -0.455], (-2.201, -0.455], (0.587, 3.132]]
Length: 30
Categories (4, interval[float64, right]): [(-2.201, -0.455] < (-0.455, 0.259] < (0.259, 0.587] < (0.587, 3.132]]

In [86]:
# we can also pass infinite values to define the bins:

arr = np.random.randn(20)

factor = pd.cut(arr, [-np.inf, 0, np.inf])

factor

[(0.0, inf], (-inf, 0.0], (-inf, 0.0], (0.0, inf], (0.0, inf], ..., (-inf, 0.0], (0.0, inf], (-inf, 0.0], (-inf, 0.0], (0.0, inf]]
Length: 20
Categories (2, interval[float64, right]): [(-inf, 0.0] < (0.0, inf]]

## Function Application

 - Methods to apply your own or another library's funcions to pandas objects,
 
 - Tableswise Function Application": `pipe()`
 - Row or Column-wise Function Application: `apply()`
 - Aggragation API: `agg()` and `transform()`
 - Applying Elementwise Functions: `map()`

### Tablewise function application

In [90]:
# If the function needs to be called in a chain use the `pipe` method:

def extract_city_name(df):
    """
    Chicago, IL -> Chicago for city_name column
    """
    df["city_name"] = df["city_and_code"].str.split(",").str.get(0)
    return df

def add_country_name(df, country_name=None):
    """
    Chicago -> Chicago-US for city_name column
    """
    col = "city_name"
    df["city_and_country"] = df[col] + country_name
    return df

df_p = pd.DataFrame({"city_and_code": ["Chicago, IL"]})

In [92]:
add_country_name(extract_city_name(df_p), country_name="US")

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

In [93]:
df_p.pipe(extract_city_name).pipe(add_country_name, country_name="US")

city_and_code city_name city_and_country
0   Chicago, IL   Chicago        ChicagoUS

### Row or column-wise function aplication

In [94]:
df.apply(lambda x: np.mean(x))

one     -0.574062
two      0.108385
three   -0.276532
dtype: float64

In [95]:
df.apply(lambda x: np.mean(x), axis=1)

a   -0.392259
b   -0.016443
c   -0.103709
d   -0.486634
dtype: float64

In [96]:
df.apply(lambda x: x.max() - x.min())

one      1.069845
two      0.329948
three    1.443609
dtype: float64

In [97]:
df.apply(np.cumsum)

one       two     three
a -1.125195  0.340677       NaN
b -1.666837  0.392730  0.440259
c -1.722187  0.403458  0.173755
d       NaN  0.433540 -0.829596

In [98]:
df.apply(np.exp)

one       two     three
a  0.324589  1.405899       NaN
b  0.581792  1.053432  1.553109
c  0.946154  1.010786  0.766053
d       NaN  1.030539  0.366649

In [100]:
# apply method will also dispatch on a string method name.

df.apply("mean")

one     -0.574062
two      0.108385
three   -0.276532
dtype: float64

In [101]:
df.apply("mean", axis=1)

a   -0.392259
b   -0.016443
c   -0.103709
d   -0.486634
dtype: float64

In [103]:
# if we wanted to extract the date where the maximum value for each column occurred:

tsdf = pd.DataFrame(
    np.random.randn(1000, 3),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=1000),
)

tsdf.apply(lambda x: x.idxmax())

A   2002-07-15
B   2000-10-14
C   2000-11-08
dtype: datetime64[ns]

In [105]:
#passing additional arguements and keyword arguements to the `apply()` method.

def subtract_and_divide(x, sub, divide=1):
    return (x - sub) / divide

df_udf = pd.DataFrame(np.ones((2, 2)))

df_udf.apply(subtract_and_divide, args=(5,), divide=3)

0         1
0 -1.333333 -1.333333
1 -1.333333 -1.333333

In [106]:
#we also have the ability to pass Series methods to carry out some series operation on each column or row:

tsdf = pd.DataFrame(
    np.random. randn(10, 3),
    columns=["A", "B", "C"],
    index = pd.date_range("1/1/2000", periods=10),
)

tsdf.iloc[3:7] = np.nan

tsdf

A         B         C
2000-01-01 -0.319435 -0.631179  0.437638
2000-01-02  0.671229 -0.338584 -0.203775
2000-01-03  0.967178  0.216012  0.206056
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -0.481147 -0.243977 -1.140375
2000-01-09 -0.057594  0.774631  0.659829
2000-01-10  0.336412  0.822289 -0.363977

In [107]:
tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01 -0.319435 -0.631179  0.437638
2000-01-02  0.671229 -0.338584 -0.203775
2000-01-03  0.967178  0.216012  0.206056
2000-01-04  0.677513  0.124014 -0.063230
2000-01-05  0.387848  0.032016 -0.332517
2000-01-06  0.098183 -0.059982 -0.601803
2000-01-07 -0.191482 -0.151979 -0.871089
2000-01-08 -0.481147 -0.243977 -1.140375
2000-01-09 -0.057594  0.774631  0.659829
2000-01-10  0.336412  0.822289 -0.363977

### Aggragation API

In [108]:
tsdf = pd.DataFrame(
    np.random.randn(10, 3),
    columns = ["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods=10),
)

tsdf.iloc[3:7] = np.nan

tsdf

A         B         C
2000-01-01 -0.833335 -0.255908 -0.039023
2000-01-02 -2.504109 -0.525393 -0.413102
2000-01-03  0.412354 -2.411540 -1.005834
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -0.262226  0.822889 -0.680796
2000-01-09  0.439303  0.860319  0.886590
2000-01-10 -1.310104  1.092191 -0.671674

In [109]:
tsdf.agg(lambda x: np.sum(x))

A   -4.058117
B   -0.417442
C   -1.923839
dtype: float64

In [110]:
tsdf.agg("sum")

A   -4.058117
B   -0.417442
C   -1.923839
dtype: float64

In [111]:
tsdf.sum()

A   -4.058117
B   -0.417442
C   -1.923839
dtype: float64

In [112]:
tsdf["A"].agg("sum")

-4.058116688675521

### Aggregation with multiple functions

In [113]:
# You can pass multiple aggregation arguements as a list.
#The list will be a row in the resulting `DataFrame`.
#These are naturally named from the aggregation function.

tsdf.agg(["sum"])

A         B         C
sum -4.058117 -0.417442 -1.923839

In [114]:
tsdf.agg(["sum", "mean"])

A         B         C
sum  -4.058117 -0.417442 -1.923839
mean -0.676353 -0.069574 -0.320640

In [115]:
tsdf["A"].agg(["sum", "mean"])

sum    -4.058117
mean   -0.676353
Name: A, dtype: float64

In [116]:
tsdf["A"].agg(["sum", lambda x: x.mean()])

sum        -4.058117
<lambda>   -0.676353
Name: A, dtype: float64

In [117]:
#passing a named function.

def mymean(x):
    return x.mean()

tsdf["A"].agg(["sum", mymean])

sum      -4.058117
mymean   -0.676353
Name: A, dtype: float64

In [118]:
### Aggregation with a dict

tsdf.agg({"A": "mean", "B":"sum"})

A   -0.676353
B   -0.417442
dtype: float64

In [119]:
tsdf.agg({"A": ["mean", "min"], "B":"sum"})

A         B
mean -0.676353       NaN
min  -2.504109       NaN
sum        NaN -0.417442

### Custom describe

 - with `.agg()` it is possible to easily create a custom describe function, similar to the built in `describe function`.

In [120]:
from functools import partial

q_25 = partial(pd.Series.quantile, q=0.25)

q_25.__name__ = "25%"

q_75 = partial(pd.Series.quantile, q=0.75)

q_75.__name__ = "75%"

tsdf.agg(["count", "mean", "std", "min", q_25, "median", q_75,"max"])

A         B         C
count   6.000000  6.000000  6.000000
mean   -0.676353 -0.069574 -0.320640
std     1.128578  1.321982  0.673452
min    -2.504109 -2.411540 -1.005834
25%    -1.190912 -0.458022 -0.678516
median -0.547780  0.283491 -0.542388
75%     0.243709  0.850961 -0.132543
max     0.439303  1.092191  0.886590

### Transform API

 - The `transform` method returns an object that is indexed the same (same size) as the original. This API allows you to provide multiple operations at the same time rather than one-by-one. Its API is quite similar to the `.agg` API.

In [121]:
tsdf = pd.DataFrame(
    np.random.randn(10, 3),
    columns=["A", "B", "C"],
    index=pd.date_range("1/1/2000", periods = 10),
)

tsdf.iloc[3:7] = np.nan

tsdf

A         B         C
2000-01-01  0.898126  1.267756 -0.290938
2000-01-02 -1.384374 -1.412709 -0.597569
2000-01-03  0.655223 -0.911748  1.064058
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.763035  2.309574  1.162176
2000-01-09  1.189094 -1.635591  1.915306
2000-01-10  0.998465 -0.164047 -0.992503

In [122]:
tsdf.transform(np.abs)

A         B         C
2000-01-01  0.898126  1.267756  0.290938
2000-01-02  1.384374  1.412709  0.597569
2000-01-03  0.655223  0.911748  1.064058
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.763035  2.309574  1.162176
2000-01-09  1.189094  1.635591  1.915306
2000-01-10  0.998465  0.164047  0.992503

In [123]:
tsdf.transform("abs")

A         B         C
2000-01-01  0.898126  1.267756  0.290938
2000-01-02  1.384374  1.412709  0.597569
2000-01-03  0.655223  0.911748  1.064058
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.763035  2.309574  1.162176
2000-01-09  1.189094  1.635591  1.915306
2000-01-10  0.998465  0.164047  0.992503

In [124]:
tsdf.transform(lambda x: x.abs())

A         B         C
2000-01-01  0.898126  1.267756  0.290938
2000-01-02  1.384374  1.412709  0.597569
2000-01-03  0.655223  0.911748  1.064058
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.763035  2.309574  1.162176
2000-01-09  1.189094  1.635591  1.915306
2000-01-10  0.998465  0.164047  0.992503

In [125]:
# `transform()` receiving a single function is similar to the `ufunc` application.

np.abs(tsdf)

A         B         C
2000-01-01  0.898126  1.267756  0.290938
2000-01-02  1.384374  1.412709  0.597569
2000-01-03  0.655223  0.911748  1.064058
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.763035  2.309574  1.162176
2000-01-09  1.189094  1.635591  1.915306
2000-01-10  0.998465  0.164047  0.992503

In [130]:
tsdf["A"].transform(np.abs)

2000-01-01    0.898126
2000-01-02    1.384374
2000-01-03    0.655223
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
2000-01-08    0.763035
2000-01-09    1.189094
2000-01-10    0.998465
Freq: D, Name: A, dtype: float64

### Transform with multiple functions

In [131]:
# Passing multiple functions will yield a column MultiIndexed DataFrame.
#The first level will be the original frame column names;
#The second level will be the names of the transforming functions.

tsdf.transform([np.abs, lambda x: x + 1])

A                   B                   C          
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  0.898126  1.898126  1.267756  2.267756  0.290938  0.709062
2000-01-02  1.384374 -0.384374  1.412709 -0.412709  0.597569  0.402431
2000-01-03  0.655223  1.655223  0.911748  0.088252  1.064058  2.064058
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  0.763035  1.763035  2.309574  3.309574  1.162176  2.162176
2000-01-09  1.189094  2.189094  1.635591 -0.635591  1.915306  2.915306
2000-01-10  0.998465  1.998465  0.164047  0.835953  0.992503  0.007497

In [133]:
tsdf["A"].transform([np.abs, lambda x: x + 1])

absolute  <lambda>
2000-01-01  0.898126  1.898126
2000-01-02  1.384374 -0.384374
2000-01-03  0.655223  1.655223
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  0.763035  1.763035
2000-01-09  1.189094  2.189094
2000-01-10  0.998465  1.998465

### Transforming with a dict

In [134]:
tsdf.transform({"A": np.abs, "B": lambda x: x + 1})

A         B
2000-01-01  0.898126  2.267756
2000-01-02  1.384374 -0.412709
2000-01-03  0.655223  0.088252
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  0.763035  3.309574
2000-01-09  1.189094 -0.635591
2000-01-10  0.998465  0.835953

In [136]:
tsdf.transform({"A": np.abs, "B": [lambda x: x + 1, "sqrt"]})

C:\Users\arnol\anaconda3\Lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)


A         B          
            absolute  <lambda>      sqrt
2000-01-01  0.898126  2.267756  1.125947
2000-01-02  1.384374 -0.412709       NaN
2000-01-03  0.655223  0.088252       NaN
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.763035  3.309574  1.519728
2000-01-09  1.189094 -0.635591       NaN
2000-01-10  0.998465  0.835953       NaN

### Applying elementwise functions

 - Since not all functions can be vectorized (accept Numpy arrays and return another array or value), the methods `maps()` and DataFrame and analogously `map()` on Series accept any Python function taking a single value and returning a single value.

In [137]:
df4 = df.copy()

df4

one       two     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [138]:
def f(x):
    return len(str(x))

df4["one"].map(f)

a    19
b    19
c    21
d     3
Name: one, dtype: int64

In [141]:
df4.maps(f)

AttributeError: 'DataFrame' object has no attribute 'maps'

In [142]:
# Series .map() has an additional feature, tha can easily "link" or "map" values,
# defined by a secondary series. This closely related to `merging/joining functionality:`

s = pd.Series(
    ["six", "seven", "six", "seven", "six"], index=["a", "b", "c", "d", "e"]
)


t = pd.Series({"six": 6.0, "seven": 7.0})

s

a      six
b    seven
c      six
d    seven
e      six
dtype: object

In [143]:
s.map(t)

a    6.0
b    7.0
c    6.0
d    7.0
e    6.0
dtype: float64

## Reindexing and altering labels

- To reindex means to conform the data to match a given set of labels along a particular axis. This accomplishes several things:

 - Reorders the existing data to match a new set of labels.
 - Inserts missing value (NA) markers in label locations where no data for that label existed.
 - If specified, fill data for missing labels using logic (highly relevant to working with time series data).

In [144]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

s

a   -1.887069
b   -0.270645
c    0.572851
d    1.959950
e    0.907754
dtype: float64

In [145]:
s.reindex(["e", "b", "f", "d"])

e    0.907754
b   -0.270645
f         NaN
d    1.959950
dtype: float64

In [146]:
df

one       two     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [147]:
df.reindex(index=["c", "f", "b"], columns=["three", "two", "one"])

three       two       one
c -0.266504  0.010728 -0.055350
f       NaN       NaN       NaN
b  0.440259  0.052053 -0.541642

In [148]:
rs = s.reindex(df.index)

rs

a   -1.887069
b   -0.270645
c    0.572851
d    1.959950
dtype: float64

In [149]:
rs.index is df.index

True

In [150]:
df.reindex(["c", "f", "b"], axis="index")

one       two     three
c -0.055350  0.010728 -0.266504
f       NaN       NaN       NaN
b -0.541642  0.052053  0.440259

In [151]:
df.reindex(["three", "two", "one"], axis="columns")

three       two       one
a       NaN  0.340677 -1.125195
b  0.440259  0.052053 -0.541642
c -0.266504  0.010728 -0.055350
d -1.003350  0.030082       NaN

### Reindexing to align with another object

In [152]:
df2 = df.reindex(["a", "b", "c"], columns=["one", "two"])

df3 = df2 - df2.mean()

df2

one       two
a -1.125195  0.340677
b -0.541642  0.052053
c -0.055350  0.010728

In [153]:
df3

one       two
a -0.551133  0.206190
b  0.032421 -0.082433
c  0.518712 -0.123758

In [154]:
df.reindex_like(df2)

one       two
a -1.125195  0.340677
b -0.541642  0.052053
c -0.055350  0.010728

### Aligning objects with each other with align

 - The `align()` method is the fastest way to simultaneously align two objects It supports a `join` arguement (related to `joining and merging`):

In [ ]:
# join = 'outer' : take the union of the indexes(default).
#join = 'left' : use the calling objects index.
#join='right' : use the passed objects index.
#join = 'inner' : intersect the indexes.

In [155]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

s1 = s[:4]

s2 = s[1:]

s1.align(s2)

(a    0.867227
 b   -0.243644
 c    0.018528
 d    0.178316
 e         NaN
 dtype: float64,
 a         NaN
 b   -0.243644
 c    0.018528
 d    0.178316
 e   -0.742136
 dtype: float64)

In [156]:
s1.align(s2, join="inner")

(b   -0.243644
 c    0.018528
 d    0.178316
 dtype: float64,
 b   -0.243644
 c    0.018528
 d    0.178316
 dtype: float64)

In [157]:
s1.align(s2, join="left")

(a    0.867227
 b   -0.243644
 c    0.018528
 d    0.178316
 dtype: float64,
 a         NaN
 b   -0.243644
 c    0.018528
 d    0.178316
 dtype: float64)

In [158]:
df.align(df2, join="inner")

(        one       two
 a -1.125195  0.340677
 b -0.541642  0.052053
 c -0.055350  0.010728,
         one       two
 a -1.125195  0.340677
 b -0.541642  0.052053
 c -0.055350  0.010728)

In [159]:
df.align(df2, join="inner", axis=0)

(        one       two     three
 a -1.125195  0.340677       NaN
 b -0.541642  0.052053  0.440259
 c -0.055350  0.010728 -0.266504,
         one       two
 a -1.125195  0.340677
 b -0.541642  0.052053
 c -0.055350  0.010728)

In [160]:
# I you pass a series to DataFrame.align(), you can choose to align both objects either on,
# the DataFrame's index or columns using the `axis` argument:

df.align(df2.iloc[0], axis=1)

(        one     three       two
 a -1.125195       NaN  0.340677
 b -0.541642  0.440259  0.052053
 c -0.055350 -0.266504  0.010728
 d       NaN -1.003350  0.030082,
 one     -1.125195
 three         NaN
 two      0.340677
 Name: a, dtype: float64)

### Filling while reindexing

In [161]:
rng = pd.date_range("1/3/2000", periods=8)

ts = pd.Series(np.random.randn(8), index=rng)

ts2 = ts.iloc[[0, 3, 6]]

ts

2000-01-03   -0.327841
2000-01-04   -1.372495
2000-01-05    2.570118
2000-01-06   -0.140007
2000-01-07   -0.513433
2000-01-08   -0.104438
2000-01-09   -0.900742
2000-01-10    1.402704
Freq: D, dtype: float64

In [162]:
ts2

2000-01-03   -0.327841
2000-01-06   -0.140007
2000-01-09   -0.900742
Freq: 3D, dtype: float64

In [163]:
ts2.reindex(ts.index)

2000-01-03   -0.327841
2000-01-04         NaN
2000-01-05         NaN
2000-01-06   -0.140007
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -0.900742
2000-01-10         NaN
Freq: D, dtype: float64

In [164]:
ts2.reindex(ts.index, method="ffill")

2000-01-03   -0.327841
2000-01-04   -0.327841
2000-01-05   -0.327841
2000-01-06   -0.140007
2000-01-07   -0.140007
2000-01-08   -0.140007
2000-01-09   -0.900742
2000-01-10   -0.900742
Freq: D, dtype: float64

In [165]:
ts2.reindex(ts.index, method="bfill")

2000-01-03   -0.327841
2000-01-04   -0.140007
2000-01-05   -0.140007
2000-01-06   -0.140007
2000-01-07   -0.900742
2000-01-08   -0.900742
2000-01-09   -0.900742
2000-01-10         NaN
Freq: D, dtype: float64

In [166]:
ts2.reindex(ts.index, method="nearest")

2000-01-03   -0.327841
2000-01-04   -0.327841
2000-01-05   -0.140007
2000-01-06   -0.140007
2000-01-07   -0.140007
2000-01-08   -0.900742
2000-01-09   -0.900742
2000-01-10   -0.900742
Freq: D, dtype: float64

In [167]:
ts2.reindex(ts.index).ffill()

2000-01-03   -0.327841
2000-01-04   -0.327841
2000-01-05   -0.327841
2000-01-06   -0.140007
2000-01-07   -0.140007
2000-01-08   -0.140007
2000-01-09   -0.900742
2000-01-10   -0.900742
Freq: D, dtype: float64

### Limits on filling while reindexing

 - `limit` and `tolerance` arguments provide additional control over filling while reindexing. Limit specifies the maximum count of consecutive matches.

In [169]:
ts2.reindex(ts.index, method="ffill", limit=1)

2000-01-03   -0.327841
2000-01-04   -0.327841
2000-01-05         NaN
2000-01-06   -0.140007
2000-01-07   -0.140007
2000-01-08         NaN
2000-01-09   -0.900742
2000-01-10   -0.900742
Freq: D, dtype: float64

In [170]:
ts2.reindex(ts.index, method="ffill", tolerance="1 day")

2000-01-03   -0.327841
2000-01-04   -0.327841
2000-01-05         NaN
2000-01-06   -0.140007
2000-01-07   -0.140007
2000-01-08         NaN
2000-01-09   -0.900742
2000-01-10   -0.900742
Freq: D, dtype: float64

- When used on a `DatetimeIndex`, `TimedeltaIndex` or `PeriodIndex`, `tolerance` will coerced into a `Timedelta` if possible. This allows you to specify tolerance with appropriate strings.

### Dropping labels froman axis.

 - A method closely related to `reindex` is the `drop()` function. It removes a set of labels from axis:

In [171]:
df

one       two     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [172]:
df.drop(["a", "d"], axis=0)

one       two     three
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504

In [173]:
df.drop(["one"], axis=1)

two     three
a  0.340677       NaN
b  0.052053  0.440259
c  0.010728 -0.266504
d  0.030082 -1.003350

In [174]:
# The following also works:

df.reindex(df.index.difference(["a", "d"]))

one       two     three
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504

### Renaming / mapping labels

 - The `rename()` method allows you to relabel an axis based on some mapping (a dict or Series) or an arbitrary function.

In [175]:
s

a    0.867227
b   -0.243644
c    0.018528
d    0.178316
e   -0.742136
dtype: float64

In [176]:
s.rename(str.upper)

A    0.867227
B   -0.243644
C    0.018528
D    0.178316
E   -0.742136
dtype: float64

In [177]:
df.rename(
    columns={"one": "foo", "two": "bar"},
    index={"a": "apple", "b": "banana", "d": "durian"},
)


foo       bar     three
apple  -1.125195  0.340677       NaN
banana -0.541642  0.052053  0.440259
c      -0.055350  0.010728 -0.266504
durian       NaN  0.030082 -1.003350

 - DataFrame.rename() also supports an “axis-style” calling convention, where you specify a single mapper and the axis to apply that mapping to.

In [178]:
df.rename({"one": "foo", "two": "bar"}, axis="columns")

foo       bar     three
a -1.125195  0.340677       NaN
b -0.541642  0.052053  0.440259
c -0.055350  0.010728 -0.266504
d       NaN  0.030082 -1.003350

In [179]:
df.rename({"a": "apple", "b": "banana", "d": "durian"}, axis="index")

one       two     three
apple  -1.125195  0.340677       NaN
banana -0.541642  0.052053  0.440259
c      -0.055350  0.010728 -0.266504
durian       NaN  0.030082 -1.003350

In [180]:
# Finally, rename() also accepts a scalar or list-like for altering the Series.name attribute.

s.rename("scalar-name")

a    0.867227
b   -0.243644
c    0.018528
d    0.178316
e   -0.742136
Name: scalar-name, dtype: float64

 - The methods DataFrame.rename_axis() and Series.rename_axis() allow specific names of a MultiIndex to be changed (as opposed to the labels).

In [182]:
df = pd.DataFrame(
    {
        "x": [1, 2, 3, 4, 5,6], "y": [10, 20, 30, 40, 50, 60]
    },
    index=pd.MultiIndex.from_product(
        [["a", "b", "c"], [1,2]], names=["let", "num"]
    ),
)

df

x   y
let num       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [183]:
df.rename_axis(index={"let":"abc"})

x   y
abc num       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [184]:
df.rename_axis(index=str.upper)

x   y
LET NUM       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

## Iteration

Basic iteration for `for i in object` produces:
- Series: values
- DataFrame: column labels

In [185]:
df = pd.DataFrame(
    {"col1": np.random.randn(3), "col2": np.random.randn(3)}, index=["a", "b", "c"]
)


for col in df:
    print(col)


col1
col2


iterrows(): Iterate over the rows of a DataFrame as (index, Series) pairs. This converts the rows to Series objects, which can change the dtypes and has some performance implications.

itertuples(): Iterate over the rows of a DataFrame as namedtuples of the values. This is a lot faster than iterrows(), and is in most cases preferable to use to iterate over the values of a DataFrame.

### Items

 - Series: (index, scalar value) pairs.
 - DataFrame: (column, Series) pairs.

In [186]:
for label, ser in df.items():
    print(label)
    print(ser)

col1
a    0.600734
b   -1.632065
c   -0.468669
Name: col1, dtype: float64
col2
a    0.178763
b   -0.601892
c   -0.908572
Name: col2, dtype: float64


### Iterrows

In [188]:
# dtypes are preserved across columns for DataFrames.
for row_index, row in df.iterrows():
    print(row_index, row, sep="\n")

a
col1    0.600734
col2    0.178763
Name: a, dtype: float64
b
col1   -1.632065
col2   -0.601892
Name: b, dtype: float64
c
col1   -0.468669
col2   -0.908572
Name: c, dtype: float64


### Itertuples

In [190]:
for row in df.itertuples():
    print(row)

Pandas(Index='a', col1=0.6007342229787576, col2=0.1787629212931642)
Pandas(Index='b', col1=-1.6320650625485575, col2=-0.6018919131897188)
Pandas(Index='c', col1=-0.46866905215820714, col2=-0.9085722572554168)


## .dt accessor

In [191]:
# an accessor to succintly return datetime like properties for the values of the Series.

In [192]:
s = pd.Series(pd.date_range("20130101 09:10:12", periods=4))

s

0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
dtype: datetime64[ns]

In [193]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int32

In [194]:
s.dt.second

0    12
1    12
2    12
3    12
dtype: int32

In [195]:
s.dt.day

0    1
1    2
2    3
3    4
dtype: int32

In [197]:
s[s.dt.day == 2]

1   2013-01-02 09:10:12
dtype: datetime64[ns]

In [198]:
stz = s.dt.tz_localize("US/Eastern")

stz

0   2013-01-01 09:10:12-05:00
1   2013-01-02 09:10:12-05:00
2   2013-01-03 09:10:12-05:00
3   2013-01-04 09:10:12-05:00
dtype: datetime64[ns, US/Eastern]

In [199]:
# Chaining these operations.
s.dt.tz_localize("UTC").dt.tz_convert("US/Eastern")

0   2013-01-01 04:10:12-05:00
1   2013-01-02 04:10:12-05:00
2   2013-01-03 04:10:12-05:00
3   2013-01-04 04:10:12-05:00
dtype: datetime64[ns, US/Eastern]

You can also format datetime values as strings with `Series.dt.strftime()` which supports the same format as the standard `strftime()`.

In [200]:
s = pd.Series(pd.date_range("20130101", periods=4))

s

0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
dtype: datetime64[ns]

In [201]:
s.dt.strftime("%Y/%m/%d")

0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object

In [203]:
s = pd.Series(pd.timedelta_range("1 day 00:00:05", periods=4, freq="s"))

s

0   1 days 00:00:05
1   1 days 00:00:06
2   1 days 00:00:07
3   1 days 00:00:08
dtype: timedelta64[ns]

In [204]:
s.dt.components

days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     1      0        0        5             0             0            0
1     1      0        0        6             0             0            0
2     1      0        0        7             0             0            0
3     1      0        0        8             0             0            0

## vectorized string methods

In [205]:
s = pd.Series(
    ["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"], dtype="string"
)
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5    <NA>
6    caba
7     dog
8     cat
dtype: string

## Sorting

Pandas supports thre kinds of sorting:
 - sorting buy index labels
 - sorting by column values
 - sorting by a combination both.

In [207]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

unsorted_df = df.reindex(
    index=["a", "d", "c", "b"], columns=["three", "two", "one"]
)

unsorted_df

three       two       one
a       NaN -0.461554  0.051899
d  0.267815  1.366116       NaN
c  0.101010 -1.724636  1.560700
b  0.889206 -0.114723 -0.087727

In [208]:
unsorted_df.sort_index(ascending=False)

three       two       one
d  0.267815  1.366116       NaN
c  0.101010 -1.724636  1.560700
b  0.889206 -0.114723 -0.087727
a       NaN -0.461554  0.051899

In [209]:
unsorted_df.sort_index(axis=1)

one     three       two
a  0.051899       NaN -0.461554
d       NaN  0.267815  1.366116
c  1.560700  0.101010 -1.724636
b -0.087727  0.889206 -0.114723

In [210]:
unsorted_df["three"].sort_index()

a         NaN
b    0.889206
c    0.101010
d    0.267815
Name: three, dtype: float64

In [212]:
s1 = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3], "c": [2, 3, 4]}).set_index(
    list("ab")
)
s1

c
a b   
B 1  2
a 2  3
C 3  4

In [213]:
s1.sort_index(level="a")

c
a b   
B 1  2
C 3  4
a 2  3

In [214]:
s1.sort_index(level="a", key=lambda idx: idx.str.lower())

c
a b   
a 2  3
B 1  2
C 3  4

### By values

In [216]:
df1 = pd.DataFrame(
    {"one": [2, 1, 1, 1], "two": [1, 3, 2, 4], "three": [5, 4, 3, 2]}
)

df1.sort_values(by="two")

one  two  three
0    2    1      5
2    1    2      3
1    1    3      4
3    1    4      2

In [217]:
df1[["one", "two", "three"]].sort_values(by=["one", "two"])

one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

In [221]:
s[2] = np.nan

s.sort_values()

0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
2    <NA>
5    <NA>
dtype: string

In [222]:
s.sort_values(na_position = "first")

2    <NA>
5    <NA>
0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
dtype: string

In [223]:
s1 = pd.Series(["B", "a", "C"])

In [224]:
s1.sort_values()

0    B
2    C
1    a
dtype: object

In [225]:
s1.sort_values(key=lambda x: x.str.lower())

1    a
0    B
2    C
dtype: object

In [226]:
df = pd.DataFrame({"a": ["B", "a", "C"], "b": [1, 2, 3]})

In [227]:
df.sort_values(by="a")

a  b
0  B  1
2  C  3
1  a  2

In [228]:
df.sort_values(by="a", key=lambda col: col.str.lower())

a  b
1  a  2
0  B  1
2  C  3

### By indexes and values

In [229]:
idx = pd.MultiIndex.from_tuples(
    [("a", 1), ("a", 2), ("a", 2), ("b", 2), ("b", 1), ("b", 1)]
)

idx.names = ["first", "second"]

In [230]:
df_multi = pd.DataFrame({"A": np.arange(6, 0, -1)}, index=idx)

df_multi

A
first second   
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

In [231]:
df_multi.sort_values(by=["second", "A"])

A
first second   
b     1       1
      1       2
a     1       6
b     2       3
a     2       4
      2       5

### searchsorted

In [232]:
ser = pd.Series([1, 2, 3])

ser.searchsorted([0, 3])

array([0, 2], dtype=int64)

In [233]:
ser.searchsorted([0, 4])

array([0, 3], dtype=int64)

In [234]:
ser.searchsorted([1, 3], side="right")

array([1, 3], dtype=int64)

In [235]:
ser.searchsorted([1, 3], side="left")

array([0, 2], dtype=int64)

In [236]:
ser = pd.Series([3, 1, 2])

In [237]:
ser.searchsorted([0, 3], sorter=np.argsort(ser))

array([0, 2], dtype=int64)

### smallest / largest values
 - Series has the nsmallest() and nlargest() methods which return the smallest or largest 
 - values. For a large Series this can be much faster than sorting the entire Series and calling head(n) on the result.

In [238]:
s = pd.Series(np.random.permutation(10))

s

0    6
1    8
2    1
3    7
4    0
5    3
6    9
7    5
8    2
9    4
dtype: int32

In [239]:
s.sort_values()

4    0
2    1
8    2
5    3
9    4
7    5
0    6
3    7
1    8
6    9
dtype: int32

In [240]:
s.nsmallest(3)

4    0
2    1
8    2
dtype: int32

In [241]:
s.nlargest(3)

6    9
1    8
3    7
dtype: int32

In [242]:
df = pd.DataFrame(
    {
        "a": [-2, -1, 1, 10, 8, 11, -1],
        "b": list("abdceff"),
        "c": [1.0, 2.0, 4.0, 3.2, np.nan, 3.0, 4.0],
    }
)

In [243]:
df.nlargest(3, "a")

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN

In [244]:
df.nlargest(5, ["a", "c"])

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN
2   1  d  4.0
6  -1  f  4.0

In [245]:
df.nsmallest(3, "a")

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0

In [246]:
df.nsmallest(5, ["a", "c"])

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0
2  1  d  4.0
4  8  e  NaN

### Sorting by a MultiIndex column

In [247]:
df1.columns = pd.MultiIndex.from_tuples(
    [("a", "one"), ("a", "two"), ("b", "three")]
)

df1.sort_values(by=("a", "two"))

a         b
  one two three
0   2   1     5
2   1   2     3
1   1   3     4
3   1   4     2

In [249]:
# Finding the number of columns of each type in a DataFrame.
dft = pd.DataFrame(
    {
        "A": np.random.rand(3),
        "B": 1,
        "C": "foo",
        "D": pd.Timestamp("20010102"),
        "E": pd.Series([1.0] * 3).astype("float32"),
        "F": False,
        "G": pd.Series([1] * 3, dtype="int8"),
    }
)

dft.dtypes.value_counts()

float64           1
int64             1
object            1
datetime64[ns]    1
float32           1
bool              1
int8              1
Name: count, dtype: int64

### Defaults

- By default integer types are `int64` and float types are `float64` regardless of platform (32-bit or 64-bit).

In [250]:
# The following will all result in `int64` dtypes.
pd.DataFrame([1, 2], columns=["a"]).dtypes

a    int64
dtype: object

In [251]:
pd.DataFrame({"a": 1}, index=list(range(2))).dtypes

a    int64
dtype: object

In [252]:
pd.DataFrame({"a": [1, 2]}).dtypes

a    int64
dtype: object

In [253]:
# The following will result in `int32` on 32-bit platform

frame = pd.DataFrame(np.array([1, 2]))

### Upcasting
- Types can potentially be upcasted when combined with other types, meaning tey are promoted from the current type (e.g `int` to `float`)

In [254]:
df3 = df1.reindex_like(df2).fillna(value=0.0) + df2

df3

one       two
a -1.125195  0.340677
b -0.541642  0.052053
c -0.055350  0.010728

In [255]:
df3.dtypes

one    float64
two    float64
dtype: object

### astype

- can be used to explicitly convert dtypes from one to another

In [256]:
df3.astype("float32").dtypes

one    float32
two    float32
dtype: object

In [257]:
dft = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})

dft[["a", "b"]] = dft[["a", "b"]].astype(np.uint8)

dft

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [258]:
dft1 = pd.DataFrame({"a": [1, 0, 1], "b": [4, 5, 6], "c": [7, 8, 9]})

dft1 = dft1.astype({"a": np.bool_, "c": np.float64})

dft1

a  b    c
0   True  4  7.0
1  False  5  8.0
2   True  6  9.0

In [259]:
dft1.dtypes

a       bool
b      int64
c    float64
dtype: object

### object conversion

In [260]:
import datetime

df = pd.DataFrame(
    [
        [1, 2],
        ["a", "b"],
        [datetime.datetime(2016, 3, 2), datetime.datetime(2016, 3, 2)],
    ]
)


df = df.T

df

0  1          2
0  1  a 2016-03-02
1  2  b 2016-03-02

In [261]:
df.dtypes

0            object
1            object
2    datetime64[ns]
dtype: object

In [262]:
df.infer_objects().dtypes

0             int64
1            object
2    datetime64[ns]
dtype: object

In [263]:
m = ["1.1", 2, 3]

pd.to_numeric(m)

array([1.1, 2. , 3. ])

In [264]:
import datetime

m = ["2016-07-09", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m)

DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [265]:
m = ["5us", pd.Timedelta("1day")]

pd.to_timedelta(m)

TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)

In [266]:
# handling different data types.
import datetime

m = ["apple", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m, errors="coerce")

C:\Users\arnol\AppData\Local\Temp\ipykernel_15120\1373490557.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(m, errors="coerce")


DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [267]:
m = ["apple", 2, 3]

pd.to_numeric(m, errors="coerce")

array([nan,  2.,  3.])

In [268]:

m = ["apple", pd.Timedelta("1day")]

pd.to_timedelta(m, errors="coerce")

TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)

In [269]:
# `Ignore` ignores the data type conversion and returns the original value.

m = ["apple", datetime.datetime(2016, 3, 2)]

pd.to_datetime(m, errors="ignore")

C:\Users\arnol\AppData\Local\Temp\ipykernel_15120\1997718526.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(m, errors="ignore")


Index(['apple', 2016-03-02 00:00:00], dtype='object')

## Selecting columns based on dtypes

In [271]:
df = pd.DataFrame(
    {
        "string": list("abc"),
        "int64": list(range(1, 4)),
        "uint8": np.arange(3, 6).astype("u1"),
        "float64": np.arange(4.0, 7.0),
        "bool1": [True, False, True],
        "bool2": [False, True, False],
        "dates": pd.date_range("now", periods=3),
        "category": pd.Series(list("ABC")).astype("category"),
    }
)

In [272]:
df["tdeltas"] = df.dates.diff()

df["uint64"] = np.arange(3, 6).astype("u8")

df["other_dates"] = pd.date_range("20130101", periods=3)

df["tz_aware_dates"] = pd.date_range("20130101", periods=3, tz="US/Eastern")

df

string  int64  uint8  float64  bool1  bool2                      dates  \
0      a      1      3      4.0   True  False 2024-01-03 16:07:04.383813   
1      b      2      4      5.0  False   True 2024-01-04 16:07:04.383813   
2      c      3      5      6.0   True  False 2024-01-05 16:07:04.383813   

  category tdeltas  uint64 other_dates            tz_aware_dates  
0        A     NaT       3  2013-01-01 2013-01-01 00:00:00-05:00  
1        B  1 days       4  2013-01-02 2013-01-02 00:00:00-05:00  
2        C  1 days       5  2013-01-03 2013-01-03 00:00:00-05:00